"""#806 per-request REQUEST Guard Runtime Binding persistence."""

from datetime import datetime
from uuid import UUID

from sqlalchemy import CheckConstraint, DateTime, ForeignKeyConstraint, Index, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.core.db.databases import Base
from app.core.db.types import UUIDChar
from rag_runtime.request_authority import RequestAuthorityDecisionOutcome, RequestAuthorityDecisionStage
from rag_runtime.runtime_environment import RuntimeEnvironmentCode


def _sql_in_list(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{value}'" for value in values)


_OUTCOMES = tuple(item.value for item in RequestAuthorityDecisionOutcome)
_ENVIRONMENTS = tuple(item.value for item in RuntimeEnvironmentCode)


class RagRequestGuardRuntimeBinding(Base):
    """Historical facts bound to one authoritative REQUEST instance.

    The request instance ID is supplied by the authoritative evaluator and is the immutable row
    identity. It is never generated by a downstream reader. Semantic artifact identity is stored
    separately so Worker consumers can exact-read and recompute it.
    """

    __tablename__ = "rag_request_guard_runtime_binding"
    __table_args__ = (
        UniqueConstraint(
            "artifact_code",
            "artifact_version",
            "artifact_content_sha256",
            name="uq_rag_request_guard_runtime_binding_artifact",
        ),
        ForeignKeyConstraint(
            ["bundle_id", "bundle_manifest_hash"],
            ["rag_runtime_release_bundle.id", "rag_runtime_release_bundle.bundle_manifest_hash"],
            name="fk_rag_request_guard_runtime_binding_bundle",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            [
                "legacy_request_guard_artifact_code",
                "legacy_request_guard_artifact_version",
                "legacy_request_guard_content_sha256",
            ],
            [
                "rag_request_guard_authority.artifact_code",
                "rag_request_guard_authority.artifact_version",
                "rag_request_guard_authority.artifact_content_sha256",
            ],
            name="fk_rag_request_guard_runtime_binding_legacy_guard",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="fk_rag_request_guard_runtime_binding_user",
            ondelete="RESTRICT",
        ),
        CheckConstraint(
            "artifact_code = 'request_guard_runtime_binding'",
            name="chk_rag_request_guard_runtime_binding_artifact_code",
        ),
        CheckConstraint(
            "length(trim(artifact_version)) > 0",
            name="chk_rag_request_guard_runtime_binding_artifact_version_nonblank",
        ),
        CheckConstraint(
            "artifact_content_sha256 ~ '^[0-9a-f]{64}$'",
            name="chk_rag_request_guard_runtime_binding_content_sha256",
        ),
        CheckConstraint(
            f"actual_decision_outcome IN ({_sql_in_list(_OUTCOMES)})",
            name="chk_rag_request_guard_runtime_binding_outcome",
        ),
        CheckConstraint(
            f"decision_stage = '{RequestAuthorityDecisionStage.REQUEST.value}'",
            name="chk_rag_request_guard_runtime_binding_stage",
        ),
        CheckConstraint(
            f"environment_code IN ({_sql_in_list(_ENVIRONMENTS)})",
            name="chk_rag_request_guard_runtime_binding_environment",
        ),
        CheckConstraint(
            "bundle_manifest_hash ~ '^[0-9a-f]{64}$'",
            name="chk_rag_request_guard_runtime_binding_bundle_hash",
        ),
        CheckConstraint(
            "jsonb_typeof(request_scope_codes) = 'array' AND jsonb_array_length(request_scope_codes) > 0",
            name="chk_rag_request_guard_runtime_binding_scopes",
        ),
        CheckConstraint(
            "scope_manifest_hash ~ '^[0-9a-f]{64}$'",
            name="chk_rag_request_guard_runtime_binding_scope_hash",
        ),
        CheckConstraint(
            "legacy_request_guard_artifact_code = 'request_guard_authority'",
            name="chk_rag_request_guard_runtime_binding_legacy_code",
        ),
        CheckConstraint(
            "legacy_request_guard_content_sha256 ~ '^[0-9a-f]{64}$'",
            name="chk_rag_request_guard_runtime_binding_legacy_hash",
        ),
        Index("idx_rag_request_guard_runtime_binding_user", "user_id"),
        Index("idx_rag_request_guard_runtime_binding_bundle", "bundle_id", "bundle_manifest_hash"),
    )

    request_guard_decision_id: Mapped[UUID] = mapped_column(UUIDChar(), primary_key=True)
    artifact_code: Mapped[str] = mapped_column(String(100), nullable=False)
    artifact_version: Mapped[str] = mapped_column(String(50), nullable=False)
    artifact_content_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    actual_decision_outcome: Mapped[str] = mapped_column(String(10), nullable=False)
    user_id: Mapped[UUID] = mapped_column(UUIDChar(), nullable=False)
    request_operation_code: Mapped[str] = mapped_column(String(100), nullable=False)
    decision_stage: Mapped[str] = mapped_column(String(20), nullable=False)
    environment_code: Mapped[str] = mapped_column(String(50), nullable=False)
    bundle_id: Mapped[UUID] = mapped_column(UUIDChar(), nullable=False)
    bundle_manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    request_scope_codes: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    scope_manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    legacy_request_guard_artifact_code: Mapped[str] = mapped_column(String(100), nullable=False)
    legacy_request_guard_artifact_version: Mapped[str] = mapped_column(String(50), nullable=False)
    legacy_request_guard_content_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
