"""Track C Safety·Barrier·ActionPlan 저장 계약입니다."""

from enum import StrEnum


class SafetyResponseLevel(StrEnum):
    ROUTINE = "ROUTINE"
    URGENT = "URGENT"
    EMERGENCY = "EMERGENCY"
    UNKNOWN = "UNKNOWN"


class SafetyDisposition(StrEnum):
    NORMAL = "NORMAL"
    URGENT_ROUTED = "URGENT_ROUTED"
    EMERGENCY_ROUTED = "EMERGENCY_ROUTED"
    BLOCKED_ACTION = "BLOCKED_ACTION"
    UNKNOWN_RISK = "UNKNOWN_RISK"


class BarrierResponseStatus(StrEnum):
    ANSWERED = "ANSWERED"
    DECLINED = "DECLINED"


class BarrierCode(StrEnum):
    FORGOT = "FORGOT"
    SCHEDULE_OR_TRAVEL = "SCHEDULE_OR_TRAVEL"
    INSTRUCTIONS_UNCLEAR = "INSTRUCTIONS_UNCLEAR"
    NEED_DOUBT = "NEED_DOUBT"
    MEDICATION_CONCERN = "MEDICATION_CONCERN"
    ACCESS_OR_COST = "ACCESS_OR_COST"


class SupportCode(StrEnum):
    REMINDER_SETUP = "REMINDER_SETUP"
    ROUTINE_OR_TRAVEL_PLAN = "ROUTINE_OR_TRAVEL_PLAN"
    INSTRUCTION_REVIEW = "INSTRUCTION_REVIEW"
    PURPOSE_REVIEW = "PURPOSE_REVIEW"
    MEDICATION_CONCERN_GUIDANCE = "MEDICATION_CONCERN_GUIDANCE"
    ACCESS_SUPPORT = "ACCESS_SUPPORT"


class SupportActionPlanStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ActionPlanFollowupResponse(StrEnum):
    HELPED = "HELPED"
    NOT_HELPED = "NOT_HELPED"
    NOT_SURE = "NOT_SURE"
