"""Backend와 AI Worker가 공유하는 RAG 실행 구현입니다."""

from rag_runtime.identification_preflight import (
    MANIFEST_PROJECTION_VERSION,
    IdentificationSnapshotRef,
    MedicationIdentificationPreflightOutcome,
    MedicationIdentificationPreflightRequest,
    MedicationPreflightState,
    MedicationSnapshotRef,
    PreflightCurrentnessToken,
    PreflightDecision,
    PreflightExecutionStatus,
    PreflightReason,
    PreflightStaleProjection,
    PreflightStaleSignal,
    PreflightValidationCode,
    canonical_preflight_manifest_hash,
    evaluate_medication_identification_preflight,
    medication_ids_in_manifest_order,
    preflight_state_from_mapping,
    project_preflight_stale_signal,
    project_preflight_stale_signals,
)

__all__ = [
    "MANIFEST_PROJECTION_VERSION",
    "IdentificationSnapshotRef",
    "MedicationIdentificationPreflightOutcome",
    "MedicationIdentificationPreflightRequest",
    "MedicationPreflightState",
    "MedicationSnapshotRef",
    "PreflightCurrentnessToken",
    "PreflightDecision",
    "PreflightExecutionStatus",
    "PreflightReason",
    "PreflightStaleProjection",
    "PreflightStaleSignal",
    "PreflightValidationCode",
    "canonical_preflight_manifest_hash",
    "evaluate_medication_identification_preflight",
    "medication_ids_in_manifest_order",
    "preflight_state_from_mapping",
    "project_preflight_stale_signal",
    "project_preflight_stale_signals",
]
