"""create initial sqlalchemy tables

Revision ID: fbee479a0129
Revises:
Create Date: 2026-08-18 22:32:17.905174

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbee479a0129"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("email", sa.String(length=40), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender", native_enum=False, length=10), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "medical_document",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("user_id", sa.CHAR(length=36), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("upload_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "ocr_job",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("document_id", sa.CHAR(length=36), nullable=False),
        sa.Column("ocr_status", sa.String(length=20), nullable=False),
        sa.Column("engine_name", sa.String(length=100), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("ocr_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name="ck_ocr_job_status"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["medical_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "document_id", name="uq_ocr_job_id_document_id"),
    )
    op.create_index("ix_ocr_job_document_created", "ocr_job", ["document_id", "created_at", "id"], unique=False)
    op.create_table(
        "extracted_field",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("ocr_job_id", sa.CHAR(length=36), nullable=False),
        sa.Column("medication_index", sa.Integer(), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("raw_value", sa.String(length=1000), nullable=True),
        sa.Column("confirmed_value", sa.String(length=1000), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confirmation_status", sa.String(length=20), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(confirmation_status = 'UNCONFIRMED' AND confirmed_value IS NULL AND confirmed_at IS NULL) OR (confirmation_status = 'CONFIRMED' AND confirmed_value IS NOT NULL AND confirmed_at IS NOT NULL)",
            name="ck_extracted_field_confirmation",
        ),
        sa.CheckConstraint(
            "(field_type = 'PRESCRIBED_DATE' AND medication_index = 0) OR (field_type <> 'PRESCRIBED_DATE' AND medication_index > 0)",
            name="ck_extracted_field_medication_index",
        ),
        sa.CheckConstraint(
            "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)",
            name="ck_extracted_field_confidence",
        ),
        sa.ForeignKeyConstraint(["ocr_job_id"], ["ocr_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ocr_job_id", "medication_index", "field_type", name="uq_extracted_field_job_medication_type"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("extracted_field")
    op.drop_table("ocr_job")
    op.drop_table("medical_document")
    op.drop_table("user")
