"""add ocr job created sequence

Revision ID: f4c2a1b7d9e3
Revises: b194e393dba7
Create Date: 2026-08-24 09:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4c2a1b7d9e3"
down_revision: str | Sequence[str] | None = "b194e393dba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_CREATED_SEQUENCE_TYPE = sa.BigInteger().with_variant(
    mysql.BIGINT(unsigned=True),
    "mysql",
)


def _upgrade_mysql() -> None:
    """PR #65까지의 MySQL 동작을 그대로 유지합니다."""
    op.execute("SET @ocr_job_created_sequence := 0")
    op.execute(
        """
        UPDATE ocr_job
        SET created_sequence =
            (@ocr_job_created_sequence := @ocr_job_created_sequence + 1)
        ORDER BY created_at ASC, id ASC
        """
    )

    op.alter_column(
        "ocr_job",
        "created_sequence",
        existing_type=_CREATED_SEQUENCE_TYPE,
        nullable=False,
        server_default=sa.text("(UUID_SHORT())"),
    )


def _upgrade_postgresql() -> None:
    """기존 행을 결정적으로 백필하고 PostgreSQL identity를 연결합니다."""
    bind = op.get_bind()

    # 같은 created_at을 가진 행도 id로 순서를 고정해 재현 가능한 값을 만듭니다.
    op.execute(
        """
        WITH ranked_jobs AS (
            SELECT
                id,
                ROW_NUMBER() OVER (
                    ORDER BY created_at ASC, id ASC
                ) AS sequence_value
            FROM ocr_job
        )
        UPDATE ocr_job AS target
        SET created_sequence = ranked_jobs.sequence_value
        FROM ranked_jobs
        WHERE target.id = ranked_jobs.id
        """
    )

    op.alter_column(
        "ocr_job",
        "created_sequence",
        existing_type=sa.BigInteger(),
        nullable=False,
    )

    maximum_sequence = bind.execute(
        sa.text(
            """
            SELECT COALESCE(MAX(created_sequence), 0)
            FROM ocr_job
            """
        )
    ).scalar_one()
    identity_start = int(maximum_sequence) + 1

    # BY DEFAULT를 사용해 신규 행은 자동 생성하고,
    # MySQL 이관 시에는 기존 값을 명시적으로 삽입할 수 있게 합니다.
    op.execute(
        sa.text(
            "ALTER TABLE ocr_job "
            "ALTER COLUMN created_sequence "
            "ADD GENERATED BY DEFAULT AS IDENTITY "
            f"(START WITH {identity_start})"
        )
    )


def upgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    op.add_column(
        "ocr_job",
        sa.Column(
            "created_sequence",
            _CREATED_SEQUENCE_TYPE,
            nullable=True,
        ),
    )

    if dialect_name == "mysql":
        _upgrade_mysql()
    elif dialect_name == "postgresql":
        _upgrade_postgresql()
    else:
        # 알 수 없는 DB에서 부분 적용되는 것을 방지합니다.
        raise RuntimeError(f"지원하지 않는 DB dialect입니다: {dialect_name}")

    # 기존 인덱스는 document_id FK 지원을 위해 유지하고,
    # 최신 OCR 결과의 결정적 정렬에 사용할 인덱스를 추가합니다.
    op.create_index(
        "idx_ocr_document_created_seq",
        "ocr_job",
        ["document_id", "created_at", "created_sequence"],
    )


def downgrade() -> None:
    # PostgreSQL identity sequence는 컬럼 소유이므로 컬럼 삭제 시 함께 제거됩니다.
    op.drop_index(
        "idx_ocr_document_created_seq",
        table_name="ocr_job",
    )
    op.drop_column("ocr_job", "created_sequence")
